# Generated by Django 4.1.3 on 2022-11-20 12:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('breaking', models.DateTimeField(verbose_name='breaking')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('condition', models.CharField(choices=[('running', 'running'), ('broken', 'broken')], default='running', max_length=7, verbose_name='condition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('axis', django.contrib.gis.db.models.fields.PointField(blank=True, default=100, null=True, srid=4326, verbose_name='coordinate')),
                ('distans', models.IntegerField(verbose_name='distans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='command initiator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
